spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5433/springApi?createDatabaseIfNotExist=true
    username: demouser
    password: demouser
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 7200 # 2hours / 5 minutes 900
    refreshTokenExpiration: 604800 # 7d
stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}
websiteUrl: http://localhost:4242