spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/springApi?createDatabaseIfNotExist=true
    username: demouser
    password: demouser
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242